name: DistributedMobSpawns
version: 2.0.0
main: me.kickash32.distributedmobspawns.DistributedMobSpawns
commands:
  dms:
    description: Configure and test DistributedMobSpawns
    usage: use /dms help to view commands
    permission: dms.debug
    permission-message: You don't have dms.debug